./validate.sh ../xsdrt/maindoc/UBL-CreditNote-2.0.xsd ../xml/UBL-CreditNote-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-DespatchAdvice-2.0.xsd ../xml/UBL-DespatchAdvice-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-Invoice-2.0.xsd ../xml/UBL-Invoice-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-Order-2.0.xsd ../xml/UBL-Order-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-OrderResponseSimple-2.0.xsd ../xml/UBL-OrderResponseSimple-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-Quotation-2.0.xsd ../xml/UBL-Quotation-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-ReceiptAdvice-2.0.xsd ../xml/UBL-ReceiptAdvice-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-RemittanceAdvice-2.0.xsd ../xml/UBL-RemittanceAdvice-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-RequestForQuotation-2.0.xsd ../xml/UBL-RequestForQuotation-2.0-Example.xml
./validate.sh ../xsdrt/maindoc/UBL-Statement-2.0.xsd ../xml/UBL-Statement-2.0-Example.xml
